services:
  endee:
    image: endeeio/endee-server:latest
    container_name: endee-server
    ports:
      - "8080:8080"
    ulimits:
      nofile:
        soft: 100000
        hard: 100000
    logging:
      driver: "json-file"
      options:
        max-size: "200m"
        max-file: "5"
    environment:
      NDD_NUM_THREADS: 0        # 0 = auto-detect all CPU threads
      NDD_AUTH_TOKEN: ""        # Leave empty — no auth needed for local dev
    volumes:
      - endee-data:/data
    restart: unless-stopped

volumes:
  endee-data:
